consul5:
   image: consul
   ports:
    - "8400:8400"
    - "8500:8500"
   volumes:
    - ./consul/config:/consul/config
    - ./consul/bin:/consul/bin
hipster_cache5:
   image: golang:1.7
   ports: 
    - "4000:4000"
    - "4003:4003"
   command: go run /go/src/hipster-cache/cmd/main.go -config=/go/src/hipster-cache/etc/application.json
   volumes:
    - ./hipster-cache:/go/src/hipster-cache
   links:
    - consul5
   environment:
    - CONSUL_URL=consul5:8500
    - SERVER_IP=hipster_cache5
    - EXTERNAL_IP=hipster_cache5
    - METRICS_PORT=4000
    - SERVER_PORT=4003
hipster_cache2_1:
   image: golang:1.7
   ports: 
    - "4021:4021"
    - "4022:4022"
   command: go run /go/src/hipster-cache/cmd/main.go -config=/go/src/hipster-cache/etc/application.json
   volumes:
    - ./hipster-cache:/go/src/hipster-cache
   links:
    - consul5
   environment:
    - CONSUL_URL=consul5:8500
    - SERVER_IP=hipster_cache2_1
    - EXTERNAL_IP=hipster_cache2_1
    - METRICS_PORT=4021
    - SERVER_PORT=4022
hipster_cache3_1:
   image: golang:1.7
   ports: 
    - "4031:4031"
    - "4032:4032"
   command: go run /go/src/hipster-cache/cmd/main.go -config=/go/src/hipster-cache/etc/application.json
   volumes:
    - ./hipster-cache:/go/src/hipster-cache
   links:
    - consul5
   environment:
    - CONSUL_URL=consul5:8500
    - SERVER_IP=hipster_cache3_1
    - EXTERNAL_IP=hipster_cache3_1
    - METRICS_PORT=4031
    - SERVER_PORT=4032
hipster_client:
  image: golang:1.7
  ports:
   - "4041:4041"
#  command: go test /go/src/hipster-cache-client/test/...
  command: sleep 10000
  volumes:
    - ./hipster-cache-client:/go/src/hipster-cache-client
  links:
    - hipster-cache-proxy4
    - hipster_cache5
    - hipster_cache2_1
    - hipster_cache3_1
  environment:
    - PROXY_ADDRESS=hipster-cache-proxy4
    - PROXY_PORT=4001
hipster-cache-proxy4:
   image: golang:1.7
   ports: 
    - "4001:4001"
    - "4002:4002"
    - "4004:4004"
   command: go run /go/src/hipster-cache-proxy/cmd/main.go -config=/go/src/hipster-cache-proxy/etc/application.json
   volumes:
    - ./hipster-cache-proxy:/go/src/hipster-cache-proxy
   links:
    - consul5
    - hipster_cache5
    - hipster_cache2_1
    - hipster_cache3_1
prometheus2:
   image: prom/prometheus
   volumes:
    - ./prometheus:/etc/prometheus
   ports:
    - "9090:9090"
   links:
    - hipster_cache5
    - hipster_cache2_1
    - hipster_cache3_1
    - hipster-cache-proxy4
    - consul5
grafana:
   image: grafana/grafana
   ports:
     - "3001:3000"
   links:
     - prometheus2
   environment:
     - GF_SERVER_ROOT_URL=http://grafana.net
