consul5:
   image: consul
   ports:
    - "8400:8400"
    - "8500:8500"
   volumes:
    - ./consul/config:/consul/config
    - ./consul/bin:/consul/bin
#   links:
#    - hipster-cache-proxy
#   command: consul agent -server -bind=127.0.0.1 -client=0.0.0.0
#   environment:
#    - CONSUL_LOCAL_CONFIG={"acl_datacenter":"dc1","acl_default_policy":"deny","acl_down_policy":"extend-cache","acl_master_token":"the_one_ring","bootstrap_expect":1,"datacenter":"dc1","data_dir":"/usr/local/bin/consul.d/data","server":true} 
hipster_cache5:
   image: golang:1.7 
   ports: 
    - "4000:4000"
    - "4003:4003"
   command: go run /go/src/hipster-cache/cmd/main.go -config=/go/src/hipster-cache/etc/application.json
   volumes:
    - /Users/Jack/PhpstormProjects/go/src/hipster-cache:/go/src/hipster-cache
   links:
    - consul5
   environment:
    - CONSUL_URL=consul5:8500 
    - SERVER_IP=hipster_cache5 
    - METRICS_PORT=4000
    - SERVER_PORT=4003
hipster_cache2_1:
   image: golang:1.7 
   ports: 
    - "4021:4021"
    - "4022:4022"
#   command: sleep 100000
   command: go run /go/src/hipster-cache/cmd/main.go -config=/go/src/hipster-cache/etc/application.json
   volumes:
    - /Users/Jack/PhpstormProjects/go/src/hipster-cache:/go/src/hipster-cache
   links:
    - consul5
   environment:
    - CONSUL_URL=consul5:8500 
    - SERVER_IP=hipster_cache2_1 
    - METRICS_PORT=4021
    - SERVER_PORT=4022
hipster_cache3_1:
   image: golang:1.7 
   ports: 
    - "4031:4031"
    - "4032:4032"
#   command: sleep 100000
   command: go run /go/src/hipster-cache/cmd/main.go -config=/go/src/hipster-cache/etc/application.json
   volumes:
    - /Users/Jack/PhpstormProjects/go/src/hipster-cache:/go/src/hipster-cache
   links:
    - consul5
   environment:
    - CONSUL_URL=consul5:8500 
    - SERVER_IP=hipster_cache3_1 
    - METRICS_PORT=4031
    - SERVER_PORT=4032
#hipster_cache_bin:
#   build: cache-server2 
#   ports: 
#   - "4010:4010"
#   - "4011:4011"
#   command: /go/bin/hipster-cache -config=/go/bin/etc/application.json
#  links:
#   - consul5
#hipster_cache_proxy_bin:
#   build: cache-proxy
#   ports: 
#    - "5012:5012"
#   - "5013:5013"
#   - "5014:5014"
#   command: /go/bin/hipster-cache-proxy -config=/go/bin/etc/application.json
#   links:
#   - consul5
hipster-cache-proxy4:
   image: golang:1.7 
   ports: 
    - "4001:4001"
    - "4002:4002"
    - "4004:4004"
   command: sleep 100000
   volumes:
    - /Users/Jack/PhpstormProjects/go/src/hipster-cache-proxy:/go/src/hipster-cache-proxy
   links:
    - consul5
    - hipster_cache5
    - hipster_cache2_1
    - hipster_cache3_1
prometheus2:
   image: prom/prometheus
   volumes:
    - ./prometheus:/etc/prometheus
   ports:
    - "9090:9090"
   links:
    - hipster_cache5
    - hipster-cache-proxy4
    - consul5
grafana:
   image: grafana/grafana
   ports:
     - "3001:3000"
   links:
     - prometheus2
   environment: 
     - GF_SERVER_ROOT_URL=http://grafana.net
