apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  selector:
    app: consul
  type: LoadBalancer
  ports:
  - name: ui-port
    protocol: TCP
    port: 8500
    targetPort: 8500
  - name: alt-port2
    protocol: TCP
    port: 8400
    targetPort: 8400
