apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
data:
  local.json: |-
    {"acl_datacenter":"dc1","acl_default_policy":"allow","acl_down_policy":"extend-cache","acl_master_token":"the_one_ring","bootstrap_expect":1,"datacenter":"dc1","data_dir":"/usr/local/bin/consul.d/data","server":true, "ui": true, "services": [ {"id": "hipster-cache","name": "hipster-cache"}]}
