kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zone: europe-west1-d
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    grafana.io/scrape: 'true'
  labels:
    name: grafana
  name: grafana
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:3.1.1
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: graf_pass
        ports:
        - name: web
          containerPort: 3000
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-volume
      volumes:
      - name: grafana-volume
        persistentVolumeClaim:
          claimName: grafana-data
