apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:v1.2.1
        args:
          - "-config.file=/etc/prometheus/prometheus.yml"
          - "-alertmanager.url=http://localhost:9093"
          - "-storage.local.path=/prometheus-data"
          - "-web.console.libraries=/etc/prometheus/console_libraries"
          - "-web.console.templates=/etc/prometheus/consoles"
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - mountPath: /prometheus-data
          name: prometheus-data-volume
      - name: alertmanager
        image: quay.io/prometheus/alertmanager:v0.5.0-beta.0
        args:
          - "-config.file=/etc/config/alertmanager.yml"
        ports:
        - name: web
          containerPort: 9093
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      - name: prometheus-data-volume
        persistentVolumeClaim:
          claimName: prom-data
