apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: "gcr.io/metal-cascade-146909/proxy:0.16"
        imagePullPolicy: Always
        env:
        - name: CONSUL_URL
          valueFrom:
            configMapKeyRef:
              name: consul
              key: url
        - name: SERVER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: http
          containerPort: 4001
        - name: metrics 
          containerPort: 4002
        - name: client 
          containerPort: 4004
        volumeMounts:
        - name: config-volume
          mountPath: /go/bin/etc
      volumes:
      - name: config-volume
        configMap:
          name: proxy-config
