apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: "gcr.io/metal-cascade-146909/server:0.1"
        imagePullPolicy: Always
        env:
        - name: CONSUL_URL
          valueFrom:
            configMapKeyRef:
              name: consul 
              key: url
        ports:
        - name: http
          containerPort: 4011
        - name: metrics 
          containerPort: 4012
        - name: client 
          containerPort: 4014
        volumeMounts:
        - name: config-volume
          mountPath: /go/bin/etc
      volumes:
      - name: config-volume
        configMap:
          name: server-config
