apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server2
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: server2
    spec:
      containers:
      - name: server2
        image: "gcr.io/metal-cascade-146909/server:0.12"
        imagePullPolicy: Always
        env:
        - name: CONSUL_URL
          valueFrom:
            configMapKeyRef:
              name: consul 
              key: url
        - name: SERVER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EXTERNAL_IP
          value: 104.155.86.180
        ports:
        - name: http
          containerPort: 4011
        - name: metrics 
          containerPort: 4012
        - name: client 
          containerPort: 4014
        volumeMounts:
        - name: config-volume
          mountPath: /go/bin/etc
      volumes:
      - name: config-volume
        configMap:
          name: server-config
